import React,{useMemo,useState} from 'react';
import {api, ApiError} from '../api/client';
import InstrumentTabs from '../components/InstrumentTabs';
import Disclaimer from '../components/Disclaimer';

const tabs=['Вклад','Накопительный счёт','ОФЗ','Корпоративная облигация','Фонд денежного рынка','Облигационный фонд','Индексный фонд','Акция как класс риска'];
const labels:Record<string,string>={amount:'Сумма',annual_rate_pct:'Ставка, % годовых',term_months:'Срок, месяцев',capitalization:'Капитализация процентов',early_withdrawal:'Досрочное снятие',tax_pct:'Налог, %',min_balance:'Минимальный остаток',years_to_maturity:'Срок до погашения, лет',clean_price_pct:'Цена, % от номинала',coupon_pct:'Купон, %',commission_pct:'Комиссия, %',default_risk_pct:'Кредитный риск, %',expected_return_pct:'Ожидаемая доходность, %',management_fee_pct:'Комиссия фонда, % в год',stress_drawdown_pct:'Стресс-просадка, %'};
const defaults:any={'Вклад':{amount:1000000,annual_rate_pct:12,term_months:12,capitalization:true,early_withdrawal:false,tax_pct:13},'Накопительный счёт':{amount:1000000,annual_rate_pct:10,term_months:12,min_balance:500000,withdrawals_allowed:true,tax_pct:13},'ОФЗ':{amount:1000000,coupon_pct:10,years_to_maturity:3,clean_price_pct:96,commission_pct:0.2,tax_pct:13},'Корпоративная облигация':{amount:1000000,coupon_pct:12,years_to_maturity:3,clean_price_pct:95,commission_pct:0.3,default_risk_pct:2,tax_pct:13},'Фонд денежного рынка':{amount:1000000,expected_return_pct:10,management_fee_pct:0.5,term_months:12,tax_pct:13},'Облигационный фонд':{amount:1000000,expected_return_pct:12,management_fee_pct:1,term_months:24,tax_pct:13},'Индексный фонд':{amount:1000000,expected_return_pct:16,management_fee_pct:1.2,term_months:36,tax_pct:13,stress_drawdown_pct:-20},'Акция как класс риска':{amount:1000000,expected_return_pct:18,management_fee_pct:0,term_months:36,tax_pct:13,stress_drawdown_pct:-35}};

export default function InstrumentCheckPage(){const [tab,setTab]=useState(tabs[0]);const [params,setParams]=useState<any>(defaults[tabs[0]]);const [result,setResult]=useState<any>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const entries=useMemo(()=>Object.entries(params),[params]);
const onCalc=async()=>{setLoading(true);setError('');try{setResult(await api('/api/instrument/check',{method:'POST',body:JSON.stringify({selectedInstrumentType:tab,params})}));}catch(e:any){setError(e instanceof ApiError?e.message:'Ошибка расчёта');}finally{setLoading(false)}};
return <div className='grid2'><div className='card'><h1>Проверить инструмент</h1><InstrumentTabs tabs={tabs} active={tab} onSelect={(t)=>{setTab(t);setParams(defaults[t]);setResult(null);}} />{entries.map(([k,v])=><label key={k}>{labels[k]||k}{typeof v==='boolean'?<input type='checkbox' checked={v} onChange={e=>setParams({...params,[k]:e.target.checked})}/>:<input value={String(v)} onChange={e=>setParams({...params,[k]:isNaN(Number(e.target.value))?e.target.value:Number(e.target.value)})}/>}</label>)}<button className='btn' disabled={loading} onClick={onCalc}>{loading?'Считаем...':'Рассчитать последствия'}</button>{error&&<div className='risk-flag'>{error}</div>}</div>
  <div className='card soft'>{!result?<><h3>{tab}</h3><p className='muted'>Доход и риски зависят от пользовательских параметров, налогов, комиссий и ликвидности инструмента.</p><ul><li>Проверьте комиссии и налоги</li><li>Проверьте условия досрочного выхода</li><li>Сравните со своими ограничениями</li></ul><Disclaimer/></>:<><p><b>Ожидаемая стоимость:</b> {Number(result.expected_value||0).toFixed(2)}</p><p><b>Доход:</b> {Number(result.income_estimate||0).toFixed(2)}</p><p><b>Стресс:</b> {result.stress_drawdown}%</p><div className='row'><span className='pill'>{result.liquidity_label}</span><span className='pill'>{result.risk_label}</span><span className='pill'>{result.complexity_label}</span></div><p>{result.explanation}</p><h4>Риск-флаги</h4><ul>{(result.risk_flags||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul><h4>Что проверить</h4><ul>{(result.checklist||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul><p className='muted'>{(result.limitations||[]).join(' ')}</p>{tab==='Акция как класс риска'&&<p className='muted'>Это оценка класса риска, а не расчёт конкретной акции.</p>}<Disclaimer/></>}</div></div>
}
